### PR TITLE
Update Orders.php

### PR DESCRIPTION
**Pull request by piatrouski**
Directory magento/var can't even have tmp dir, and instead of creating it - error message occurs. To prevent this - use checkAndCreateFolder method and create directory in case if it's not exist

### CODE REVIEW

**Comment by srzkptrsk** [comment]
It's critical because many deployment cases have a cleaning routine of  /var directory.

**Comment by srzkptrsk** [comment]
@rholgate-turnto Could you insert fileSystem in \TurnTo\SocialCommerce\Model\Export\CanceledOrders too, because CanceledOrders inherits \TurnTo\SocialCommerce\Model\Export\Orders? When i make the PR this class wasn't implemented.

**Comment by rholgate-turnto** [comment]
@srzkptrsk Sure thing

**Comment by rholgate-turnto** [comment]
I didn't have permissions to rebase your fork or make a new branch, so I made the changes myself and it's merged:
https://github.com/turnto/magento2-turnto-socialcommerce/pull/125

**Pull request closed without merging**
